cupsfilters/catalog.c, cupsfilters/catalog.h
- `cfCatalogSearchDirLocale()` : Searches for catalog file matching locale
- `cfCatalogSearchDirLang()`: Searches for catalog file matching only language prefix
- `cfCatalogSearchDir()`: Searches for catalog file matching a preferred locale, but defaults to other locales if not found
=> add lang parameter to cfCatalogLoad() and others

cupsfilters/catalog.c, cupsfilters/catalog.h
Commit 86c010177378a32bbbb77e02fd31bed8a446e477 removed const qualifiers from certain function parameters in `cupsfilters/catalog.c` but didn't reflect those changes in `cupsfilters/catalog.h`. This commit fixes that.
=> remove const qualifier from function params

INSTALL, README.md, configure.ac
Avahi, Glib, Freetype and Zlib are used in other projects or removed as whole.
=> Remove unused dependencies

cupsfilters/bannertopdf.c, cupsfilters/catalog.c, cupsfilters/filter.c, cupsfilters/ghostscript.c, cupsfilters/image-zoom.c, cupsfilters/image.c, cupsfilters/imagetoraster.c, cupsfilters/pclmtoraster.cxx, cupsfilters/pdftoraster.cxx, cupsfilters/texttopdf.c, cupsfilters/texttotext.c
Hi Till,
I've run our internal Coverity software (which is aggregator of open source checks as cppcheck, clang etc and proprietary coverity) on libcupsfilters as part of getting new projects into Fedora and found several issues which Coverity team marks as important to fix (such as use after free, leaks, double free etc) - the list is [here](https://github.com/OpenPrinting/libcupsfilters/files/10721597/covscan-important-issues.txt).
There are fixes for the reported issues, some indenting changes and incorrect use of calloc (args were switched) - I left the commits as they are to visibility which fix belongs to which issue.
=> Coverity fixes

cupsfilters/pclmtoraster.cxx, cupsfilters/pdf.cxx, cupsfilters/pdftopdf/qpdf-xobject.cxx, cupsfilters/pwgtopdf.cxx
PointerHolder is deprecated in the qpdf v11, getting replaced with std::shared_ptr. Warnings should be fixed with qpdf v12 onwards.
=> replaced PointerHolder with shared_ptr

cupsfilters/universal.c
Some filters (like hpps from hplip) produce this MIME type, so if the client uses classic driver/printer app and the server IPP Everywhere, job fail because the library is not able to find suitable conversion.
This patch together with cups-filters PR fixes the issue.
=> universal.c: Support application/vnd.cups-postscript

cupsfilters/raster.c
Add header file `stdbool`, since we started to use `bool` in `raster_base_header()`.
=> raster.c: Fix build after last fix

cupsfilters/pdftopdf/qpdf-cm.cxx
Use unsigned int (we use the variable as string index anyway) and check if we overflow everytime we increment the variable.
Fixes #42
=> qpdf-cm.cxx: Fix possible integer overflow

cupsfilters/pdftoraster.cxx
Define _GLIBCXX_THROW to empty for C++11 and newer.
Fixes #35
=> Fix compilation with clang and libc++

cupsfilters/raster.c
Some driverless printers (EPSON L3160 in Fedora report) stopped working after commit c6175a2 if `ColorModel=RGB` is passed as option. A different CUPS color space is assigned with the fix - CUPS_CSPACE_RGB, which results in no ICC profile being assigned into Ghostscript command line.
Probably we can try other .icc profiles with CUPS_CSPACE_RGB (srgb.icc does not work with RGB color space), but I tested with reporter that using sRGB space + srgb.icc works for the printer - so the patch is to use sRGB if the driver is URF/PWG.
=> raster.c: Use sRGB if driver is pwg/urf and has ColorModel option

cupsfilters/pdftopdf/qpdf-xobject.cxx
When running the following command on [example.pdf](https://drive.google.com/file/d/10JomuzeZc-3WvSaKo0gIbBftj9V4Glro/view?usp=drive_link)
`./pdftopdf 1 1 1 1 "" example.pdf > output.pdf`
the resultant [output.pdf](https://drive.google.com/file/d/1uSo_CYob2mx6M3LqXITey7IMLoKfXlZd/view?usp=drive_link) is mangled.
This is better explained in [this bug report](https://github.com/OpenPrinting/cups-filters/issues/549).
It seems that the logic that provides the content data streams and concatenates them to form a single stream in an XObject is assuming a correct separation between the contents of successive streams.
To better illustrate: in example.pdf above (note that the sample pdf's have been run through `qpdf --qdf --recompress-flate --compress-streams=n --object-streams=disable` for …
=> Fix content data stream concatenation mangling output in cfFilterPDFToPDF

libcupsfilters.pc.in
Don't just specify `-I${includedir}/cupsfilters`,
but also `-I${includedir}` in the Cflags
in the pkgconfig file.
This way, includes prefixed with the "cupsfilters/" directory path also work.
This e.g. makes the libppd build work when
libcupsfilters is installed in a non-default path
(e.g. configured with `--prefix=$HOME/temp/cpdb`)
and libppd is configured to use that one
(e.g. by setting env variable
`PKG_CONFIG_PATH=$HOME/temp/cpdb/lib/pkgconfig/`
during configure).
Without this commit, libppd's configure would
succeed in the above scenario, but the actual build using `make` would then fail to find the cupsfilters headers:
make  all-recursive
make[1]: Entering directory '/home/michi/development/git/libppd'
make[2]: Entering directory '/home/michi/development/git/libppd'
CC …
=> pkgconfig: Add '-I${includedir}' to Cflags

.gitignore, INSTALL.md
1. Add missing dependencies for building the project
2. Add testing instructions 
3. Ignore tmp files generated during testing
=> Revise building docs and add testing instructions

cupsfilters/raster.c
If we have no output page size, but convert from PS to PDF, Ghostscript will use the input Postscript page size.
Should fix #68.
=> Don't fallback to default page size for PS->PDF

cupsfilters/ghostscript.c, cupsfilters/mupdftopwg.c
ghostcript and mupdf filter functions did not transfer error exit code from a child and rewrote the code by successful exit code from the other child.
Fixes #76
=> Fix transferring error exit status from children (Issue #76)

cupsfilters/bannertopdf.c, cupsfilters/fontembed/sfnt-subset.c, cupsfilters/ghostscript.c, cupsfilters/image-jpeg.c, cupsfilters/image-png.c, cupsfilters/image-tiff.c, cupsfilters/imagetopdf.c, cupsfilters/imagetoraster.c, cupsfilters/pdftopdf/pdftopdf.cxx, cupsfilters/pwgtopdf.cxx, cupsfilters/raster.c, cupsfilters/testfilters.c, cupsfilters/texttopdf.c
Open source static analyzer OpenScanHub found several issues regarding resource leaks, security, buffer overflows etc., which this PR aims to address.
libcupsfilters passes sanity testing with the changes.
=> Fix issues reported by OpenScanHub

cupsfilters/bannertopdf.c
I've missed the condition, because bannertopdf was missing from test suite... I'mm sorry for inconvenience.
=> bannertopdf.c: Fix segfault when printing banners/test page

INSTALL.md, configure.ac, cupsfilters/image.c, cupsfilters/texttopdf.c, cupsfilters/universal.c
The texttopdf filter is the only thing using fontconfig.  Add a configure option to build without fontconfig and don't build this filter if that is specified.
The default configure is to use fontconfig, so there shoule be no changes to existing functionality.
Also, fix a minor compiler warning when building without exif.
=> Allow building without fontconfig

cupsfilters/pdftoraster.cxx
render_page() may return NULL if the page is not properly constructed.
=> pdftoraster: Check result of render_page

cupsfilters/ghostscript.c, cupsfilters/mupdftopwg.c, cupsfilters/pdftoraster.cxx
The problem here is that the `strchr()` function may return NULL if the requested character is not provided in the input. The pointer is then dereferenced, which crashes the program.
Commit 1 fixes the NULL-pointer dereference, but has no functional change.
I additionally observed that the parsing logic is broken for `%%PDFTOPDFCollate` in some cases - in some places where this code was copied, because `p` still points to the colon character, the loop and string comparison conditions do not make sense.  Commit 2 fixes that, but it is admittedly a change in functionality, which is why I kept the two separate.  I'm perfectly fine with it if you don't want to apply that second commit.
Same PR for cups-filters 1.x branch: https://github.com/OpenPrinting/cups-filters/pull/644
=> Fix NULL-pointer dereference when parsing %PDFTOPDF comments

cupsfilters/image-zoom.c, cupsfilters/imagetoraster.c
When calculating z->xmod, z->xstep, etc., if xsize and ysize are zero, division by zero occurs. To avoid this, the xsize and ysize check for zero is added at the beginning of the function.
=> image-zoom.c: add the xsize and ysize check to zero in _cfImageZoomNew

.gitignore, Makefile.am, charset/pdf.utf-8.heavy.in, charset/pdf.utf-8.simple.in, configure.ac
Distributions might want to use a different CJK font family to support Chinese, Japanese and Korean fonts. The MR introduces `--with-cjk-fonts` configuration option which sets the fonts name.
=> configure.ac: Make CJK fonts name configurable

cupsfilters/ghostscript.c
Add new dithering (halftone) algorithms in addition to the default Ghostscript one.
Controlled either with `halftone-type` job option or `cupsHalftoneType` PPD option.
- Stochastic algotirhm is implemented in `stocht.ps` Ghostscript library, just include it if cupsHalftoneType is set to yes/true/on/stochastic.
- Foo2zjs algorithm is a PostScript code taken from foo2zjs-pstops file (don't know the name of the algorithm)
- Threshold algorithm
=> Ghostscript (gstoraster): Introduce cupsHalftoneType dithering algorithms

cupsfilters/testfilters.sh
The script is so simple that every shell should support it. This allows building libcupsfilters without bash installed again.
=> Use /bin/sh for testfilters.sh to avoid dependency on bash

.github/workflows/build.yaml, INSTALL.md, configure.ac
The recent release of PDFio 1.6.0 fixed the following issue:
- Fixed EOF comment written to the PDF (Issue [#136](https://github.com/michaelrsweet/pdfio/pull/136))
The above fix is crucial for pdf EOF comment which was "%EOF" to "%%EOF"
=> Update build system and documentation for PDFio 1.6.0
